Jc multi training
jonoco/ml-breakout pull request #33
Opened 2021-02-10 21:40 UTC by jonoco

- PlayerSupervisor and GameManager are modified to allow multiple supervisors to communicate easily with a single manager. Changes are also meant to be backwards compatible.
- New multi-instance prefabs for training agents in parallel
- Some minor fixes

2021-02-12 22:25 UTC, matzingc requested changes

2021-02-12 22:25 UTC, matzingc commented on Assets/Scripts/PlayerSupervisor.cs
> +            return;
When in a scene where the paddle is managed by a PlayerController, the PlayerState is never set to ready so the ball never launches. My initial instinct is to just add a call for PlayerSupervisor.PlayerReady() in PlayerController.Start(), but PlayerController currently doesn't have any reference to PlayerSupervisor.

2021-02-13 02:03 UTC, frich98 commented
This is really really cool - nice job! I did my testing, and everything worked as expected. I believe you've resolved Chase's issues as I was able to play the human game just fine with the most recent code (deletion of player controller) but I'll let Chase confirm the change was made was what he was expecting. I also think it made sense to reallocate PlayerController's functions to their respective homes (paddle, ball, etc.) so I'm a fan of that change even if it wasn't needed to get the game working.

2021-02-14 21:02 UTC, matzingc approved these changes
Looks good!

2021-02-14 21:03 UTC, merged